
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;




DROP TABLE IF EXISTS tasks;
CREATE TABLE IF NOT EXISTS tasks (
  id int(11) NOT NULL AUTO_INCREMENT,
  tdesc text NOT NULL,
  tdue date NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


INSERT INTO tasks (id, tdesc, tdue) VALUES(1, 'Buy eggs', '2014-07-04');
INSERT INTO tasks (id, tdesc, tdue) VALUES(2, 'Pay taxes', '2014-07-03');
